### ISSUE TITLE
Meta issue for Puppeteer 1.2.0

### ISSUE THREAD

**Issue by zploskey** [bs-puppeteer/bs-puppeteer#24]
Tasks for a release following the Puppeteer 1.2.0 release which is expected on March 15th.
- [x] #23: ElementHandle.contentFrame()
- [x] #35: addScriptTag can can take a script type
- [x] Bump Puppeteer version
- [x] Update changelog
- [x] Ship new version

Any additional API changes should be included here.

**Comment by zploskey** [comment]
Included in version 0.5.0.
